### ISSUE TITLE
cannot use pip

### ISSUE THREAD

**Issue by pmcl77** [letorbi/synoindexwatcher#13]
Hi

It's not exactly an issue with synoindexwatcher, rather an issue with my limited knowledge about python and such... 

I used to use the original script, but at some point it seemed to stop working, so I wanted to try your new version, however I get an error when trying to use pip:

`python -m ensurepip
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/usr/lib/python2.7/ensurepip/__init__.py", line 226, in _main
    default_pip=args.default_pip,
  File "/usr/lib/python2.7/ensurepip/__init__.py", line 123, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/usr/lib/python2.7/ensurepip/__init__.py", line 45, in _run_pip
    import pip
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/__init__.py", line 16, in <module>
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/vcs/subversion.py", line 9, in <module>
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/index.py", line 30, in <module>
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/wheel.py", line 32, in <module>
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/pep425tags.py", line 335, in <module>
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/pep425tags.py", line 307, in get_supported
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/pep425tags.py", line 163, in is_manylinux1_compatible
  File "/tmp/tmpBu40rY/pip-8.1.1-py2.py3-none-any.whl/pip/pep425tags.py", line 187, in have_compatible_glibc
ValueError: invalid literal for int() with base 10: '20-2014'
`
Any help would be appreciated!

**Comment by pmcl77** [comment]
after "reinstalling" i got it to work...

`wget https://bootstrap.pypa.io/get-pip.py`

and then 

`python get-pip.py`

however `python -m ensurepip` would still give me an error, but I could now install your package!

**Comment by letorbi** [comment]
Hej pmcl77,

thanks for the hint. I will recheck the steps to setup pip and update the readme if necessary.
