### ISSUE TITLE
No module named 'constants' (python 3.5.1)

### ISSUE THREAD

**Issue by webcharlyx** [letorbi/synoindexwatcher#23]
```
admin@DS:~$ python3 --version
Python 3.5.1
admin@diskstation:~$ sudo python3 -m pip install --upgrade https://github.com/letorbi/synoindexwatcher/archive/master.zip
Password: 
Collecting https://github.com/letorbi/synoindexwatcher/archive/master.zip
  Downloading https://github.com/letorbi/synoindexwatcher/archive/master.zip
     - 256kB 914kB/s
Requirement already satisfied, skipping upgrade: inotifyrecursive>=0.2.2 in /volume2/@appstore/py3k/usr/local/lib/python3.5/site-packages (from synoindexwatcher==0.7.3) (0.2.2)
Requirement already satisfied, skipping upgrade: inotify-simple in /volume2/@appstore/py3k/usr/local/lib/python3.5/site-packages (from inotifyrecursive>=0.2.2->synoindexwatcher==0.7.3) (1.2.1)
Installing collected packages: synoindexwatcher
  Found existing installation: synoindexwatcher 0.7.3
    Uninstalling synoindexwatcher-0.7.3:
      Successfully uninstalled synoindexwatcher-0.7.3
    Running setup.py install for synoindexwatcher ... done
Successfully installed synoindexwatcher-0.7.3
admin@diskstation:~$ python3 -m synoindexwatcher --help
Traceback (most recent call last):
  File "/volume2/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/volume2/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/volume2/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/__main__.py", line 31, in <module>
    import constants
ImportError: No module named 'constants'
admin@diskstation:~$ ls -alh /volume2/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/
total 20K
drwxr-xr-x 1 root root  120 Nov 28 13:18 .
drwxr-xr-x 1 root root  610 Nov 28 13:18 ..
-rw-r--r-- 1 root root 1.2K Nov 28 13:18 constants.py
-rw-r--r-- 1 root root 1.2K Nov 28 13:18 files.py
-rw-r--r-- 1 root root    0 Nov 28 13:18 __init__.py
-rw-r--r-- 1 root root 1.8K Nov 28 13:18 init.py
-rw-r--r-- 1 root root 5.9K Nov 28 13:18 __main__.py
drwxr-xr-x 1 root root  218 Nov 28 13:18 __pycache__
```

with nano I modified `__main__.py` like this:
```
from . import constants
from . import files
from . import init
```
then it workes quite fine:
```
admin@diskstation:~$ python3 -m synoindexwatcher --help
usage: __main__.py [-h] [--logfile LOGFILE]
                   [--loglevel {ERROR,WARNING,INFO,DEBUG}] [--config CONFIG]
                   [--generate-config] [--generate-init] [--pidfile PIDFILE]
                   [path [path ...]]

positional arguments:
  path                  add a directory that shall be watched

optional arguments:
  -h, --help            show this help message and exit
  --logfile LOGFILE     write log-messages into the file LOGFILE (default:
                        stdout)
  --loglevel {ERROR,WARNING,INFO,DEBUG}
                        log only messages as or more important than LOGLEVEL
                        (default: INFO)
  --config CONFIG       read the default-configuration from the file CONFIG
  --generate-config     generate and show a configuration-file and exit
  --generate-init       generate and show an init-script and exit
  --pidfile PIDFILE     set the pid-file used in the init-script
```

probably a known issue? https://stackoverflow.com/questions/47319423/import-a-module-from-both-within-same-package-and-from-outside-the-package-in-py

**Comment by letorbi** [comment]
Thanks for reporting. Should be fixed with cda82456a05cee616ed8f11a2319e83918dac981.
