### ISSUE TITLE
0.8.1 still fails on Unicode filenames

### ISSUE THREAD

**Issue by paour** [letorbi/synoindexwatcher#29]
The attempt to fix the [previously reported exception](https://github.com/letorbi/inotifyrecursive/issues/6) was not entirely successful, but I don't think I can reopen an issue so here's a new one…

After using pip to upgrade this package (resulting in `Successfully installed inotifyrecursive-0.2.3 synoindexwatcher-0.8.1` – just making sure the version numbers are as expected), I get a slightly different exception:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 203, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 185, in start
    fullpath = os.path.join(inotify.get_path(event.wd), event.name)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 16: ordinal not in range(128)
```

Obviously, though it doesn't seem to be documented in the Python man pages, `os.path.join` does expect a decoded path.

**Comment by letorbi** [comment]
Hmm, I've just tested with the filename you gave me (`1-03 Strasbourg／st. Denis.m4a`), but I cannot reproduce the error you've reported. I've tried to use the name for files and directories, created them before and after *synoindexwatcher* has been started and even checked if the error occurs during boot - but nothing.

However, I've found another bug in *inotifyrecursive* on which you should have stumbled upon as well, if you really used version 0.8.2 of *synoindexwatcher* and 0.2.3 of *inotifyrecursive*. So my assumption is that you installed the latest version of both packages, but did not actually used them. Did you restart *synoindexwatcher* after you had updated the packages?

Since I've fixed the other bug in *inotifyrecursive* you have to upgrade again anyway, so here's my suggestion how to prevent that old versions might still be running:

* `sudo python -m pip uninstall synoindexwatcher inotifyrecursive`
* `sudo reboot`
* Re-connect to your DiskStation
* `sudo python -m pip install synoindexwatcher inotifyrecursive`
* Start Synoindex Watcher

Usually this complex process should not be required for an upgrade, it's just to be sure that no old versions cause the error - hopefully ;)

If the error still occurs, it would be great if you could tell me a way how I could re-produce the error and when the error occurrs (during boot, when creating a new file, when starting *synoindexwatcher*). Especially the full path of the filename that caused the error would be great - and also the filename itself, if it's different from the one in the original issue.

BTW: Creating a new issue is 100% correct here, because the error occurred in the *synoindexwatcher* package this time and not in the *inotifyrecursive* package.

**Comment by paour** [comment]
Here's what I did:

- `sudo python -m pip uninstall synoindexwatcher inotifyrecursive`
- `sudo reboot`
- `python -m pip install --upgrade https://github.com/letorbi/synoindexwatcher/archive/master.zip`
   - `Successfully installed inotifyrecursive-0.2.4 synoindexwatcher-0.8.2`
- `python -m synoindexwatcher --config=/root/synoindexwatcher.conf`
   - `2019-12-12 07:23:10,143 INFO Adding watch for path: /volume4/flac`
   - `2019-12-12 07:23:10,577 INFO Adding watch for path: /volume4/photo`
   - `2019-12-12 07:23:45,537 INFO Adding watch for path: /volume4/music`
   - `2019-12-12 07:23:46,981 INFO Waiting for media file changes...`
- I renamed through DSM FileStation the file `/volume4/flac/Roy\ Hargrove/2008\ Earfood/1-03\ 1-03 Strasbourg／st. Denis2.m4a` to `/volume4/flac/Roy\ Hargrove/2008\ Earfood/1-03\ 1-03 Strasbourg／st. Denis3.m4a` (a one-char change to trigger inotify)
  - `2019-12-12 07:29:11,615 ERROR An uncaught exception occurred`

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 203, in <module>
    start()
  File "/usr/lib/python2.7/site-packages/synoindexwatcher/__main__.py", line 185, in start
    fullpath = os.path.join(inotify.get_path(event.wd), event.name)
  File "/usr/lib/python2.7/posixpath.py", line 73, in join
    path += '/' + b
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 16: ordinal not in range(128)
```

During these tests I'm running the script from a root shell instead of at boot, so I can see errors as they are triggered.

**Comment by letorbi** [comment]
Could you please post the output of the `locale` command on you DiskStation?

**Comment by paour** [comment]
```
# locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8
```

Funny that you asked that, I had just run the command hoping to figure out why when I `ssh` into the nas I can see accented characters, but when I `mosh` in, I don't. It's unrelated of course, since it's just display.

**Comment by letorbi** [comment]
I was asking because [the filesystem-encoding seems to influence the way how the *inotify-simple* package returns certain strings](https://inotify-simple.readthedocs.io/en/latest/), but our locale settings are the same.

As we're talking about it. Could you also send me the output of `python -m pip list | grep inotify-simple` and `python --version`? Just to be sure that really everything is the same on our DiskStations...

**Comment by paour** [comment]
```
# python -m pip list | grep inotify-simple
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
inotify-simple           1.1.8
# python --version
Python 2.7.1
```

**Comment by letorbi** [comment]
Ok, i was able to reproduce the error in a soemhow  "artifical" environment. I get your exception when I enter the line:

```
os.path.join(u"foo", "1-03 Strasbourg／st. Denis.m4a")
```

in the Python interpreter prompt. All other combinations of Unicode and ASCII strings work.

I now have a hypothesis of what might have gone wrong. Stay tuned :)

**Comment by letorbi** [comment]
Could you please upgrade *inotifyrecursive* to 0.2.5 and test if the error is fixed afterwards?

Use `python -m pip install --upgrade inotifyrecursive==0.2.5` to upgrade.

**Comment by paour** [comment]
Hey, it looks like you got it. At least I'm not getting a crash anymore :-). Thank you for pursuing this!
