### ISSUE TITLE
NameError: name 'inotify_simple' is not defined

### ISSUE THREAD

**Issue by sousasov** [letorbi/synoindexwatcher#32]
Hi, I have problem run synoindexwatcher.

> python3 -m synoindexwatcher --help
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/__main__.py", line 30, in <module>
    from inotifyrecursive import INotify, flags
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/inotifyrecursive/__init__.py", line 19, in <module>
    from .inotifyrecursive import  *
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/inotifyrecursive/inotifyrecursive.py", line 24, in <module>
    class INotify(inotify_simple.INotify):
NameError: name 'inotify_simple' is not defined

> 
Thanks fo reply

Its ok now. 
Update inotifyrecursive to version 0.2.6

**Comment by letorbi** [comment]
The package *inotify_simple* introduced some API changes with version 1.3.0. I assume, that you problems are related to these changes.

You can downgrade *inotify_simple* to version 1.2.1 with the the following command:

```
$ sudo pip install -Iv inotify_simple==1.2.1
```
