### ISSUE TITLE
generate init bug + 1 other bug with generated config file

### ISSUE THREAD

**Issue by sousasov** [letorbi/synoindexwatcher#33]
Init bug:

> python3 -m synoindexwatcher --generate-init
ERROR:root:An uncaught exception occurred
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/__main__.py", line 218, in <module>
    start()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/__main__.py", line 157, in start
    print(files.generateInit(sys.argv))
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/files.py", line 35, in generateInit
    args.remove("--rebuild-index")
ValueError: list.remove(x): x not in list
> 

 

Config Bug/Bug in filter

>2020-02-20 13:48:02,506 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/__main__.py", line 218, in <module>
    start()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/__main__.py", line 193, in start
    for event in inotify.read():
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/inotifyrecursive/inotifyrecursive.py", line 136, in read
    if filter != None and not filter(event.name, event.wd, flags.ISDIR):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexwatcher/__main__.py", line 90, in filter
    if blacklist != None and blacklist.search(name) != None:
TypeError: cannot use a bytes pattern on a string-like object

> 

Thanks for reply.

**Comment by letorbi** [comment]
The config bug/bug in filter should be fixed with d730a09e8df17f4a0b92c5a5f59e444521cea75a. I've relesed a new version 0.10.0, which includes the fix.

A fix for the init bug will come in the next few days...

**Comment by letorbi** [comment]
The init bug should be fixed with 346cca0943d66b4274e44f3b08389286a21d58c3. A new release 0.10.1 has been created.

You can easily update your current installation with the following command: 

```
$ sudo python -m pip install --upgrade synoindexwatcher
```

All bugs mentioned in your request should be fixed now, so I'm closing this issue. Please re-open it, if the problems persist.

**Comment by sousasov** [comment]
Hi,

now its index new files added to watched folders, but if i delete file from this folders watcher crash with,

2020-02-23 21:28:12,260 ERROR An uncaught exception occurred
Traceback (most recent call last):
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexw                                     atcher/__main__.py", line 224, in <module>
    start()
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/synoindexw                                     atcher/__main__.py", line 199, in start
    for event in inotify.read():
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/inotifyrec                                     ursive/inotifyrecursive.py", line 145, in read
    self.__add_watch_recursive(path, mask, info["filter"], event.name, event.wd)
  File "/volume1/@appstore/py3k/usr/local/lib/python3.5/site-packages/inotifyrec                                     ursive/inotifyrecursive.py", line 93, in __add_watch_recursive
    for entry in os.listdir(path):
FileNotFoundError: [Errno 2] No such file or directory: "/volume1/Filmy/Testovac                                     katorentu/test.avi__DpXyQU"


Thx for reply.

**Comment by letorbi** [comment]
I've created a [new issue](./34) from your last comment, since it is not related to the previous ones.
